"""Coder — Senior Software Engineer.

Reads planner artifacts, writes real source code into ``src/`` and records an
implementation note. The generated module is a small but genuine reconciliation
engine so the Tester has something concrete to verify.
"""

from __future__ import annotations

from models.agent_result import AgentResult
from models.artifact import ImplementationArtifact
from services.context_service import AgentContext

from agents.base.base_agent import BaseAgent

_MATCHER_SOURCE = '''"""Deterministic transaction reconciliation engine (generated by Coder)."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Transaction:
    id: str
    amount: int  # minor units (cents) to avoid float drift
    date: str


@dataclass
class Reconciliation:
    matched: list[tuple[str, str]] = field(default_factory=list)
    unmatched_left: list[str] = field(default_factory=list)
    unmatched_right: list[str] = field(default_factory=list)

    @property
    def summary(self) -> dict[str, int]:
        return {
            "matched": len(self.matched),
            "unmatched_left": len(self.unmatched_left),
            "unmatched_right": len(self.unmatched_right),
        }


def reconcile(
    left: list[Transaction], right: list[Transaction]
) -> Reconciliation:
    """Match transactions across two sources by (amount, date).

    Pure and side-effect free. Each right-side transaction matches at most one
    left-side transaction.
    """

    result = Reconciliation()
    remaining = list(right)

    for tx in left:
        match = next(
            (r for r in remaining if r.amount == tx.amount and r.date == tx.date),
            None,
        )
        if match is not None:
            result.matched.append((tx.id, match.id))
            remaining.remove(match)
        else:
            result.unmatched_left.append(tx.id)

    result.unmatched_right = [r.id for r in remaining]
    return result
'''


class CoderAgent(BaseAgent):
    name = "coder"

    def execute(self, context: AgentContext) -> AgentResult:
        if self.roadmap is not None and self.roadmap.current_feature() is not None:
            return self._execute_roadmap(context)
        return self._execute_default(context)

    # ---- roadmap mode: implement the current feature ------------------- #
    def _execute_roadmap(self, context: AgentContext) -> AgentResult:
        run_id = context.run_id
        feature = self.roadmap.current_feature()

        written = [
            self._write_source(path, content)
            for path, content in feature.source_files.items()
        ]
        rel = sorted(f"src/{p}" for p in feature.source_files)

        impl = ImplementationArtifact(
            run_id=run_id,
            created_by=self.name,
            summary=f"Implemented {feature.id} ({feature.title}): {feature.summary}",
            files_changed=rel,
            decisions=["Built strictly from the spec for this feature.",
                       "Package-relative imports; small composable modules."],
            addressed_tasks=[feature.id],
        )
        artifact = self.write_artifact(impl)
        return AgentResult(
            agent=self.name,
            success=True,
            artifacts=[artifact],
            files_written=written,
            messages=[f"Built {feature.id} ({feature.title}): "
                      f"{len(rel)} file(s) — {', '.join(rel)}."],
        )

    # ---- default mode (no roadmap) ------------------------------------- #
    def _execute_default(self, context: AgentContext) -> AgentResult:
        run_id = context.run_id

        source_path = self._write_source("reconcile.py", _MATCHER_SOURCE)
        self._write_source("__init__.py", '"""Generated source package."""\n')

        impl = ImplementationArtifact(
            run_id=run_id,
            created_by=self.name,
            summary="Implemented a deterministic reconciliation engine that "
            "matches transactions across two sources by amount and date.",
            files_changed=["src/reconcile.py", "src/__init__.py"],
            decisions=[
                "Amounts stored in integer minor units to avoid float drift.",
                "Matching is a pure function for trivial testability.",
                "Each right-side transaction matches at most one left-side row.",
            ],
            addressed_tasks=["T1", "T2", "T3"],
        )
        artifact = self.write_artifact(impl)

        return AgentResult(
            agent=self.name,
            success=True,
            artifacts=[artifact],
            files_written=[source_path],
            messages=[f"Wrote reconciliation engine to {source_path}."],
        )
