"""Deterministic transaction reconciliation engine (generated by Coder)."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Transaction:
    id: str
    amount: int  # minor units (cents) to avoid float drift
    date: str


@dataclass
class Reconciliation:
    matched: list[tuple[str, str]] = field(default_factory=list)
    unmatched_left: list[str] = field(default_factory=list)
    unmatched_right: list[str] = field(default_factory=list)

    @property
    def summary(self) -> dict[str, int]:
        return {
            "matched": len(self.matched),
            "unmatched_left": len(self.unmatched_left),
            "unmatched_right": len(self.unmatched_right),
        }


def reconcile(
    left: list[Transaction], right: list[Transaction]
) -> Reconciliation:
    """Match transactions across two sources by (amount, date).

    Pure and side-effect free. Each right-side transaction matches at most one
    left-side transaction.
    """

    result = Reconciliation()
    remaining = list(right)

    for tx in left:
        match = next(
            (r for r in remaining if r.amount == tx.amount and r.date == tx.date),
            None,
        )
        if match is not None:
            result.matched.append((tx.id, match.id))
            remaining.remove(match)
        else:
            result.unmatched_left.append(tx.id)

    result.unmatched_right = [r.id for r in remaining]
    return result
